---
version: '2.2'

services:
  base:
    build: .
    working_dir: /app
    volumes:
      - $PWD:/app

  dev:
    extends: base
    volumes:
      - ~/.aws:/root/.aws
    command: python --version

  test:
    extends: base
    command: pytest
